import React, { useState } from 'react';
import { FirewallRule } from '../types';
import { Shield, Plus, Trash2, ArrowRight, Code, Copy, Check } from 'lucide-react';

interface FirewallBuilderProps {
    rules: FirewallRule[];
    setRules: (rules: FirewallRule[]) => void;
}

const FirewallBuilder: React.FC<FirewallBuilderProps> = ({ rules, setRules }) => {
  const [newRule, setNewRule] = useState<Partial<FirewallRule>>({
      action: 'ALLOW', protocol: 'TCP', source: 'ANY', destination: 'ANY', port: 'ANY', description: ''
  });
  const [generatedConfig, setGeneratedConfig] = useState('');
  const [format, setFormat] = useState<'CISCO' | 'IPTABLES'>('CISCO');

  const addRule = () => {
    const rule: FirewallRule = {
        id: Date.now().toString(),
        sequence: (rules.length + 1) * 10,
        action: newRule.action as any,
        protocol: newRule.protocol as any,
        source: newRule.source || 'ANY',
        destination: newRule.destination || 'ANY',
        port: newRule.port || 'ANY',
        description: newRule.description || 'No description'
    };
    // Maintain deny at end if present, but for simplicity append here
    setRules([...rules, rule]);
  };

  const deleteRule = (id: string) => {
      setRules(rules.filter(r => r.id !== id));
  };

  const generateConfig = () => {
      let output = '';
      if (format === 'CISCO') {
          output += `! Cisco IOS ACL Generated by NetTans\n`;
          output += `ip access-list extended GENERATED_ACL\n`;
          rules.forEach(r => {
              const src = r.source === 'ANY' ? 'any' : r.source;
              const dst = r.destination === 'ANY' ? 'any' : `host ${r.destination}`; // Simplified
              const proto = r.protocol.toLowerCase();
              const action = r.action.toLowerCase();
              const port = r.port !== 'ANY' ? `eq ${r.port}` : '';
              
              output += ` ${r.sequence} ${action} ${proto === 'any' ? 'ip' : proto} ${src} ${dst} ${port}\n`;
          });
      } else {
          output += `# Iptables Rules Generated by NetTans\n`;
          rules.forEach(r => {
              const action = r.action === 'ALLOW' ? 'ACCEPT' : 'DROP';
              const proto = r.protocol !== 'ANY' ? `-p ${r.protocol.toLowerCase()}` : '';
              const src = r.source !== 'ANY' ? `-s ${r.source}` : '';
              const dst = r.destination !== 'ANY' ? `-d ${r.destination}` : '';
              const port = r.port !== 'ANY' ? `--dport ${r.port}` : '';
              
              output += `iptables -A FORWARD ${proto} ${src} ${dst} ${port} -j ${action} -m comment --comment "${r.description}"\n`;
          });
      }
      setGeneratedConfig(output);
  };

  return (
    <div className="flex flex-col h-full gap-6">
        {/* Top: Rule Table */}
        <div className="flex-1 bg-slate-800 rounded-xl border border-slate-700 shadow-lg flex flex-col overflow-hidden">
            <div className="p-4 border-b border-slate-700 bg-slate-900/50 flex justify-between items-center">
                <h3 className="font-bold text-white flex items-center gap-2">
                    <Shield size={18} className="text-primary-500"/> ACL Policy Builder
                </h3>
            </div>
            
            {/* Rule Input Strip */}
            <div className="p-4 bg-slate-900/30 border-b border-slate-700 grid grid-cols-12 gap-2 items-end">
                <div className="col-span-1">
                    <label className="text-xs text-slate-500 block mb-1">Action</label>
                    <select value={newRule.action} onChange={e => setNewRule({...newRule, action: e.target.value as any})} className="w-full bg-slate-800 border border-slate-600 rounded px-2 py-1 text-xs text-white">
                        <option value="ALLOW">ALLOW</option>
                        <option value="DENY">DENY</option>
                    </select>
                </div>
                <div className="col-span-1">
                    <label className="text-xs text-slate-500 block mb-1">Proto</label>
                    <select value={newRule.protocol} onChange={e => setNewRule({...newRule, protocol: e.target.value as any})} className="w-full bg-slate-800 border border-slate-600 rounded px-2 py-1 text-xs text-white">
                        <option value="TCP">TCP</option>
                        <option value="UDP">UDP</option>
                        <option value="ICMP">ICMP</option>
                        <option value="ANY">ANY</option>
                    </select>
                </div>
                <div className="col-span-3">
                     <label className="text-xs text-slate-500 block mb-1">Source IP/CIDR</label>
                     <input type="text" value={newRule.source} onChange={e => setNewRule({...newRule, source: e.target.value})} className="w-full bg-slate-800 border border-slate-600 rounded px-2 py-1 text-xs text-white font-mono"/>
                </div>
                <div className="col-span-3">
                     <label className="text-xs text-slate-500 block mb-1">Dest IP/CIDR</label>
                     <input type="text" value={newRule.destination} onChange={e => setNewRule({...newRule, destination: e.target.value})} className="w-full bg-slate-800 border border-slate-600 rounded px-2 py-1 text-xs text-white font-mono"/>
                </div>
                <div className="col-span-1">
                     <label className="text-xs text-slate-500 block mb-1">Port</label>
                     <input type="text" value={newRule.port} onChange={e => setNewRule({...newRule, port: e.target.value})} className="w-full bg-slate-800 border border-slate-600 rounded px-2 py-1 text-xs text-white font-mono"/>
                </div>
                <div className="col-span-2">
                     <label className="text-xs text-slate-500 block mb-1">Desc</label>
                     <input type="text" value={newRule.description} onChange={e => setNewRule({...newRule, description: e.target.value})} className="w-full bg-slate-800 border border-slate-600 rounded px-2 py-1 text-xs text-white"/>
                </div>
                <div className="col-span-1">
                    <button onClick={addRule} className="w-full bg-primary-600 hover:bg-primary-500 text-white rounded py-1 flex justify-center items-center h-[26px]">
                        <Plus size={14} />
                    </button>
                </div>
            </div>

            <div className="flex-1 overflow-auto">
                <table className="w-full text-left text-sm">
                    <thead className="bg-slate-900 text-slate-400 font-medium text-xs">
                        <tr>
                            <th className="p-3 w-16">Seq</th>
                            <th className="p-3 w-20">Action</th>
                            <th className="p-3 w-16">Proto</th>
                            <th className="p-3">Source</th>
                            <th className="p-3 w-8"></th>
                            <th className="p-3">Destination</th>
                            <th className="p-3 w-24">Port</th>
                            <th className="p-3">Description</th>
                            <th className="p-3 w-10"></th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-700">
                        {rules.map((rule, idx) => (
                            <tr key={rule.id} className="hover:bg-slate-700/30 group">
                                <td className="p-3 text-slate-500 font-mono">{(idx + 1) * 10}</td>
                                <td className="p-3">
                                    <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${rule.action === 'ALLOW' ? 'bg-green-500/20 text-green-500' : 'bg-red-500/20 text-red-500'}`}>
                                        {rule.action}
                                    </span>
                                </td>
                                <td className="p-3 text-slate-300">{rule.protocol}</td>
                                <td className="p-3 font-mono text-slate-300">{rule.source}</td>
                                <td className="p-3 text-slate-600"><ArrowRight size={14}/></td>
                                <td className="p-3 font-mono text-slate-300">{rule.destination}</td>
                                <td className="p-3 font-mono text-slate-400">{rule.port}</td>
                                <td className="p-3 text-slate-400 text-xs italic">{rule.description}</td>
                                <td className="p-3 text-right">
                                    <button onClick={() => deleteRule(rule.id)} className="text-slate-600 hover:text-red-400 opacity-0 group-hover:opacity-100 transition-opacity">
                                        <Trash2 size={14} />
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>

        {/* Bottom: Generated Config */}
        <div className="h-48 bg-slate-900 rounded-xl border border-slate-700 flex flex-col overflow-hidden">
             <div className="px-4 py-2 bg-slate-950 border-b border-slate-800 flex justify-between items-center">
                <div className="flex gap-4 items-center">
                    <span className="text-xs font-bold text-slate-500 uppercase flex items-center gap-2">
                        <Code size={14}/> Generated Output
                    </span>
                    <div className="flex bg-slate-800 rounded p-0.5">
                        <button onClick={() => setFormat('CISCO')} className={`px-3 py-0.5 text-xs rounded transition-colors ${format === 'CISCO' ? 'bg-slate-600 text-white' : 'text-slate-400'}`}>Cisco IOS</button>
                        <button onClick={() => setFormat('IPTABLES')} className={`px-3 py-0.5 text-xs rounded transition-colors ${format === 'IPTABLES' ? 'bg-slate-600 text-white' : 'text-slate-400'}`}>iptables</button>
                    </div>
                </div>
                <div className="flex gap-2">
                    <button onClick={generateConfig} className="flex items-center gap-1 px-3 py-1 bg-primary-600 hover:bg-primary-500 text-white text-xs rounded transition-colors">
                        Generate
                    </button>
                    <button className="flex items-center gap-1 px-3 py-1 bg-slate-800 hover:bg-slate-700 text-slate-300 text-xs rounded border border-slate-700 transition-colors">
                        <Copy size={12}/> Copy
                    </button>
                </div>
             </div>
             <textarea 
                value={generatedConfig} 
                readOnly 
                className="flex-1 bg-slate-900 p-4 text-xs font-mono text-green-400 resize-none focus:outline-none"
                placeholder="Click Generate to see the configuration preview..."
             />
        </div>
    </div>
  );
};

export default FirewallBuilder;